# Generated by Django 4.0.1 on 2022-03-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_rename_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtitulo',
            new_name='cualidad',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cuerpo',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='raza',
        ),
    ]
