# Generated by Django 4.0.1 on 2022-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_post_autor_alter_post_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.EmailField(max_length=254),
        ),
    ]
