# Generated by Django 4.0.1 on 2022-03-08 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen2',
        ),
    ]
